import { AppError,type PageType } from './contracts';
export const PAGE_TYPES:PageType[]=['note','source','concept','entity','synthesis','comparison','query']; export const MAX_MARKDOWN=262_144;
export function requireObject(value:unknown):Record<string,unknown>{ if(!value||typeof value!=='object'||Array.isArray(value))throw new AppError('validation_error','A JSON object is required.',400); return value as Record<string,unknown>; }
export function requiredString(value:unknown,field:string,min:number,max:number):string{ if(typeof value!=='string')throw new AppError('validation_error',`${field} must be a string.`,400,{field}); const result=value.trim(); if(result.length<min||result.length>max)throw new AppError('validation_error',`${field} must be between ${min} and ${max} characters.`,400,{field,min,max}); return result; }
export function optionalNullableString(value:unknown,field:string):string|null{ if(value===null||value===undefined||value==='')return null; return requiredString(value,field,1,200); }
export function requiredInteger(value:unknown,field:string,min=0,max=Number.MAX_SAFE_INTEGER):number{ if(!Number.isInteger(value)||Number(value)<min||Number(value)>max)throw new AppError('validation_error',`${field} must be an integer between ${min} and ${max}.`,400,{field,min,max}); return Number(value); }
export function pageType(value:unknown):PageType{ if(typeof value!=='string'||!PAGE_TYPES.includes(value as PageType))throw new AppError('validation_error','page_type is not supported.',400,{allowed:PAGE_TYPES}); return value as PageType; }
export function operationId(value:unknown):string{ const result=requiredString(value,'operation_id',36,36); if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(result))throw new AppError('validation_error','operation_id must be a UUID.',400,{field:'operation_id'}); return result.toLowerCase(); }
export function slugify(title:string):string{ const slug=title.normalize('NFKC').toLowerCase().replace(/[\\/\u0000-\u001f\u007f]/g,'').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'').slice(0,120); if(!slug||slug==='.'||slug==='..')throw new AppError('validation_error','The title cannot produce a safe page path.',400,{field:'title'}); return slug; }
export function extractWikiLinks(markdown:string):string[]{ const found=new Set<string>(); for(const match of markdown.matchAll(/\[\[([^\]|#]{1,200})(?:[|#][^\]]*)?\]\]/g))found.add(match[1].trim()); return [...found]; }
export function parseFrontmatter(markdown:string):Record<string,string|number|boolean|string[]>{if(!markdown.startsWith('---\n')&&!markdown.startsWith('---\r\n'))return {};const normalized=markdown.replaceAll('\r\n','\n'),end=normalized.indexOf('\n---\n',4);if(end<0)throw new AppError('validation_error','Markdown frontmatter is missing its closing --- marker.',400,{field:'markdown'});const result:Record<string,string|number|boolean|string[]>={};for(const [index,line] of normalized.slice(4,end).split('\n').entries()){if(!line.trim()||line.trimStart().startsWith('#'))continue;const match=line.match(/^([A-Za-z][A-Za-z0-9_-]{0,63}):\s*(.*)$/);if(!match)throw new AppError('validation_error','Frontmatter must use simple key: value entries.',400,{line:index+2});const [,key,raw]=match;if(raw==='true'||raw==='false')result[key]=raw==='true';else if(/^-?\d+(?:\.\d+)?$/.test(raw))result[key]=Number(raw);else if(raw.startsWith('[')&&raw.endsWith(']')){try{const value=JSON.parse(raw);if(!Array.isArray(value)||value.some((item)=>typeof item!=='string'))throw new Error();result[key]=value;}catch{throw new AppError('validation_error','Frontmatter arrays must be JSON string arrays.',400,{key});}}else result[key]=raw.replace(/^(['"])(.*)\1$/,'$2');}return result;}
export async function sha256(value:string):Promise<string>{ const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join(''); }
export async function sha256Bytes(value:ArrayBuffer):Promise<string>{ const digest=await crypto.subtle.digest('SHA-256',value); return [...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,'0')).join(''); }
export function stableJson(value:unknown):string{ if(Array.isArray(value))return `[${value.map(stableJson).join(',')}]`; if(value&&typeof value==='object')return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stableJson(item)}`).join(',')}}`; return JSON.stringify(value); }
